/**
 * Client-side dossier store backed by localStorage.
 *
 * Replaces the backend /api/ayesha/dossiers/* endpoints that relied on
 * server-side filesystem paths (.cursor/) which don't exist on Render.
 *
 * Storage key: "ayesha_dossiers" → JSON array of dossier objects.
 */

const STORAGE_KEY = 'ayesha_dossiers';

// ---------------------------------------------------------------------------
// Markdown Generation (mirrors ayesha_dossiers.py template)
// ---------------------------------------------------------------------------

/**
 * Generate a deterministic markdown dossier for a drug recommendation.
 *
 * @param {Object} drug  - Drug object from the strategy panel
 * @param {Object} ctx   - Context: { patient_id, level, scenario, mutations }
 * @returns {string} Markdown content
 */
export function generateDossierMarkdown(drug, ctx = {}) {
    const name = drug.name || drug.drug || 'Unknown';
    const confidence = Math.round((drug.confidence || 0) * 100);
    const efficacy = (drug.efficacy_score || 0).toFixed(2);
    const band = drug.clinical_band || 'N/A';
    const tier = (drug.evidence_tier || 'unknown').toUpperCase();
    const rationale = drug.rationale || 'Pathway alignment detected based on genomic profile.';
    const labelStatus = drug.label_status || 'UNKNOWN';
    const badges = (drug.badges || []).join(', ') || 'None';
    const citations = drug.citations_count || drug.citations?.length || 0;
    const mutations = (ctx.mutations || []);
    const mutationLines = mutations.length > 0
        ? mutations.map(m => `- ${m.gene || 'Unknown'} ${m.hgvs_p || ''}`).join('\n')
        : '- Varies by scenario';
    const now = new Date();
    const ts = now.toISOString().replace('T', ' ').slice(0, 19);

    return `# Clinical Intelligence Dossier: ${name}
**Generated**: ${ts}
**Patient**: ${ctx.patient_id || 'AK'}
**Analysis Level**: ${ctx.level || 'L1'} (${ctx.scenario || 'Baseline'})
**Pipeline**: Ayesha Therapy Fit v2.0 (Doctor Initiated)

---

## 1. Executive Summary
**Recommendation**: ${name}
**Confidence**: ${confidence}%
**Efficacy Score**: ${efficacy}
**Clinical Band**: ${band}
**Evidence Tier**: ${tier}

> **Rationale**: ${rationale}

---

## 2. Genomic & Biomarker Context
**Mutations Used**:
${mutationLines}

**Scenario Context**: ${ctx.scenario || 'Baseline'}

---

## 3. Regulatory & Evidence Status
**Label Status**: ${labelStatus}
**Key Badges**: ${badges}
**Citations**: ${citations} supporting papers indexed.

---

## 4. Risks & Caveats
- **Evidence Level**: This recommendation is based on ${tier.toLowerCase()} evidence.
- **Labeling**: This usage is considered **${labelStatus}**.
- **Validation**: Based on computational pathway modeling. Clinical correlation advised.

---

## 5. Mechanism & Provenance
*This dossier is a receipts-backed artifact generated by the MOAT System.*
*No LLM inferences were used to modify the core clinical assertions.*
`;
}

// ---------------------------------------------------------------------------
// CRUD helpers
// ---------------------------------------------------------------------------

function _read() {
    try {
        const raw = localStorage.getItem(STORAGE_KEY);
        return raw ? JSON.parse(raw) : [];
    } catch {
        return [];
    }
}

function _write(dossiers) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(dossiers));
}

/**
 * Save a newly-generated dossier.
 *
 * @param {Object} drug  - Full drug object
 * @param {Object} ctx   - Context { patient_id, level, scenario, mutations }
 * @returns {Object} The saved dossier metadata (includes .id for navigation)
 */
export function saveDossier(drug, ctx = {}) {
    const name = drug.name || drug.drug || 'Unknown';
    const safeName = name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
    const ts = Date.now();
    const id = `DOCTOR_${safeName}_${ts}`;

    const markdown = generateDossierMarkdown(drug, ctx);

    const entry = {
        id,
        nct_id: id,                       // compat with existing detail page
        title: `Doctor Dossier: ${name}`,
        tier: 'TOP_TIER',
        match_score: drug.efficacy_score || 0,
        has_llm_analysis: false,
        type: 'doctor_initiated',
        patient_id: ctx.patient_id || 'AK',
        created_at: new Date().toISOString(),
        markdown,
        metadata: {
            tier: 'TOP_TIER',
            match_score: drug.efficacy_score || 0,
            generated_at: new Date().toISOString(),
        },
    };

    const all = _read();
    all.unshift(entry);               // newest first
    _write(all);

    return entry;
}

/**
 * List all saved dossiers (newest first), optionally filtered.
 *
 * @param {{ tier?: string, minScore?: number }} filters
 * @returns {Array} Array of dossier metadata objects
 */
export function listDossiers(filters = {}) {
    let all = _read();

    if (filters.tier && filters.tier !== 'ALL') {
        all = all.filter(d => d.tier === filters.tier);
    }
    if (typeof filters.minScore === 'number') {
        all = all.filter(d => (d.match_score || 0) >= filters.minScore);
    }

    return all;
}

/**
 * Get a single dossier by ID.
 *
 * @param {string} id
 * @returns {Object|null}
 */
export function getDossier(id) {
    return _read().find(d => d.id === id || d.nct_id === id) || null;
}

/**
 * Delete a dossier by ID.
 *
 * @param {string} id
 */
export function deleteDossier(id) {
    const all = _read().filter(d => d.id !== id && d.nct_id !== id);
    _write(all);
}

/**
 * Compute stats from stored dossiers.
 *
 * @returns {{ total, by_tier, with_llm, avg_score }}
 */
export function getDossierStats() {
    const all = _read();
    const byTier = {};
    let withLlm = 0;
    let totalScore = 0;

    for (const d of all) {
        byTier[d.tier] = (byTier[d.tier] || 0) + 1;
        if (d.has_llm_analysis) withLlm++;
        totalScore += d.match_score || 0;
    }

    return {
        total: all.length,
        by_tier: byTier,
        with_llm: withLlm,
        avg_score: all.length ? totalScore / all.length : 0,
    };
}
