#!/usr/bin/env python3
"""
Quick test of biomarker correlation service with mock data.
"""

import sys
import json
from pathlib import Path

# Add parent dir to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "oncology-coPilot" / "oncology-backend-minimal"))

from api.services.biomarker_correlation_service import BiomarkerCorrelationService

print("⚔️ TESTING BIOMARKER CORRELATION SERVICE (MOCK DATA)")
print("="*80)

# Initialize and run with custom cohort file
mock_cohort_file = Path("data/validation/sae_cohort/sae_features_tcga_ov_platinum_MOCK.json")
service = BiomarkerCorrelationService()
service.load_data(cohort_file=mock_cohort_file)
correlations = service.compute_correlations()
top_features = service.rank_and_filter_features(correlations)
service.compute_bootstrap_cis_for_top_features(top_features)
summary = service.generate_summary(top_features)

# Save results
output_file = Path("data/validation/sae_cohort/sae_tcga_ov_platinum_biomarkers_MOCK.json")
output_file.parent.mkdir(parents=True, exist_ok=True)

from dataclasses import asdict

with open(output_file, 'w') as f:
    json.dump(asdict(summary), f, indent=2)

print(f"\n✅ Results saved to: {output_file}")
print(f"\nTop 10 Features:")
# summary.top_features is a list of dicts (as generated by BiomarkerSummary)
for i, fc in enumerate(summary.top_features[:10], 1):
    print(
        f"{i}. Feature {fc['feature_index']}: "
        f"r={fc['pearson_r']:.3f}, p={fc['pearson_p']:.2e}, d={fc['cohen_d']:.3f}, "
        f"CV={fc['cv_stability']:.2f}"
    )
