/**
 * ClinicalDossierModal Component
 * 
 * Generates a formatted clinical dossier from synthetic lethality analysis results.
 * Provides export options (copy, download) for clinical use.
 */

import React, { useMemo, useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Typography,
  Box,
  Button,
  IconButton,
  Divider,
  Paper,
  Stack,
  Chip,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  CircularProgress,
  Alert
} from '@mui/material';
import {
  Close,
  ContentCopy,
  Download,
  Print,
  Description,
  AutoAwesome
} from '@mui/icons-material';
import { useLLMExplanation } from '../hooks/useLLMExplanation';

/**
 * @param {Object} props
 * @param {boolean} props.open - Modal open state
 * @param {Function} props.onClose - Close handler
 * @param {Object} props.results - Analysis results
 * @param {Array} props.mutations - Input mutations
 * @param {Object} props.diseaseContext - {disease, subtype, stage}
 */
const ClinicalDossierModal = ({
  open,
  onClose,
  results,
  mutations = [],
  diseaseContext = {}
}) => {
  const [aiSummary, setAiSummary] = useState(null);
  const { generateExplanation, loading: aiLoading, error: aiError } = useLLMExplanation();

  // Generate AI summary for dossier
  const handleGenerateAISummary = async () => {
    if (!results) return;
    const summary = await generateExplanation(results, 'clinician');
    if (summary) {
      setAiSummary(summary);
    }
  };

  // Generate dossier content
  const dossierContent = useMemo(() => {
    if (!results) return '';

    const { disease, subtype, stage } = diseaseContext;
    const essentiality = results.essentiality || [];
    const pathways = results.pathway_analysis || {};
    const therapies = results.recommended_therapies || [];

    return `
# Clinical Dossier: Synthetic Lethality Analysis

**Generated:** ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}
**Analysis Type:** Synthetic Lethality
${aiSummary ? `\n**AI Summary Included:** Yes (Generated by LLM)` : ''}

---
${aiSummary ? `
## AI-Generated Clinical Summary

${aiSummary}

---
` : ''}

## Patient Context

| Field | Value |
|-------|-------|
| **Disease** | ${formatDisease(disease)} |
| **Subtype** | ${formatSubtype(subtype)} |
| **Stage** | ${stage || 'Not specified'} |

---

## Genetic Mutations

${mutations.map(m => `- **${m.gene}** ${m.hgvs_p || ''} (${formatConsequence(m.consequence)}) - ${m.germline_status || 'Unknown origin'}`).join('\n')}

---

## Essentiality Analysis

${essentiality.map(e => `
### ${e.gene}
- **Score:** ${(e.score * 100).toFixed(0)}% (${e.score >= 0.7 ? 'HIGH' : e.score >= 0.5 ? 'MODERATE' : 'LOW'})
- **Pathway Impact:** ${e.pathwayImpact || 'Unknown'}
- **Flags:** ${Object.entries(e.flags || {}).filter(([k, v]) => v).map(([k]) => k).join(', ') || 'None'}
`).join('\n')}

---

## Pathway Dependency Analysis

### Broken Pathways
${pathways.broken_pathways?.length > 0 ? pathways.broken_pathways.map(p => `- ❌ ${p}`).join('\n') : '- None identified'}

### Essential Backup Pathways
${pathways.essential_pathways?.length > 0 ? pathways.essential_pathways.map(p => `- ⚠️ ${p}`).join('\n') : '- None identified'}

### Double-Hit Effect
${pathways.double_hit_detected ? '✅ **DETECTED** - Multiple pathway deficiencies create amplified synthetic lethality' : '❌ Not detected'}

### Synthetic Lethality Score
**${((pathways.synthetic_lethality_score || 0) * 100).toFixed(0)}%**

---

## Therapy Recommendations

| Rank | Drug | Target | Confidence | Evidence | FDA |
|------|------|--------|------------|----------|-----|
${therapies.map((t, i) => `| ${i + 1} | **${t.drug}** | ${t.target} | ${(t.confidence * 100).toFixed(0)}% | ${t.evidence_tier} | ${t.fda_approved ? '✅' : '❌'} |`).join('\n')}

### Top Recommendation: ${therapies[0]?.drug || 'None'}

**Mechanism:** ${therapies[0]?.mechanism || 'N/A'}

**Sensitivity:** ${therapies[0]?.sensitivity || 'Unknown'}

---

## Clinical Interpretation

${generateInterpretation(results, mutations)}

---

## References

1. Synthetic lethality in DNA repair deficiency - PMID: various
2. PARP inhibitor mechanism - FDA approval documents
3. DepMap cancer dependency data - Broad Institute

---

*This analysis is provided as clinical decision support. All treatment decisions should be made by the treating physician in consultation with the patient.*

**Document Classification:** Clinical Decision Support
**Analysis System:** Synthetic Lethality Analyzer v1.0
    `.trim();
  }, [results, mutations, diseaseContext, aiSummary]);

  // Copy to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(dossierContent);
      alert('Dossier copied to clipboard!');
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  // Download as markdown
  const handleDownload = () => {
    const blob = new Blob([dossierContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `synthetic_lethality_dossier_${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Print
  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Clinical Dossier - Synthetic Lethality</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 10px; }
            h2 { color: #4a148c; margin-top: 30px; }
            h3 { color: #333; }
            table { border-collapse: collapse; width: 100%; margin: 15px 0; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f5f5f5; }
            hr { margin: 20px 0; border: none; border-top: 1px solid #eee; }
            ul { padding-left: 20px; }
            li { margin: 5px 0; }
            pre { background: #f5f5f5; padding: 15px; border-radius: 5px; overflow-x: auto; }
          </style>
        </head>
        <body>
          ${dossierContent
            .replace(/^# (.*$)/gm, '<h1>$1</h1>')
            .replace(/^## (.*$)/gm, '<h2>$1</h2>')
            .replace(/^### (.*$)/gm, '<h3>$1</h3>')
            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
            .replace(/^- (.*$)/gm, '<li>$1</li>')
            .replace(/(<li>.*<\/li>\n)+/g, '<ul>$&</ul>')
            .replace(/\n\n/g, '</p><p>')
            .replace(/---/g, '<hr>')
            .replace(/\|(.+)\|/g, (match) => {
              const cells = match.split('|').filter(c => c.trim());
              if (cells.some(c => c.includes('---'))) return '';
              return '<tr>' + cells.map(c => `<td>${c.trim()}</td>`).join('') + '</tr>';
            })
          }
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  if (!results) return null;

  const essentiality = results.essentiality || [];
  const pathways = results.pathway_analysis || {};
  const therapies = results.recommended_therapies || [];

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="md"
      fullWidth
      PaperProps={{ sx: { maxHeight: '90vh' } }}
    >
      <DialogTitle sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Stack direction="row" spacing={1} alignItems="center">
          <Description color="primary" />
          <Typography variant="h6">Clinical Dossier</Typography>
        </Stack>
        <IconButton onClick={onClose}>
          <Close />
        </IconButton>
      </DialogTitle>

      <DialogContent dividers>
        {/* Preview */}
        <Paper elevation={0} sx={{ p: 3, backgroundColor: 'grey.50', borderRadius: 2 }}>
          {/* Header */}
          <Typography variant="h5" gutterBottom fontWeight="bold" color="primary.dark">
            Synthetic Lethality Analysis Report
          </Typography>
          <Typography variant="body2" color="text.secondary" gutterBottom>
            Generated: {new Date().toLocaleString()}
          </Typography>

          <Divider sx={{ my: 2 }} />

          {/* AI Summary Section */}
          <Box sx={{ mb: 3 }}>
            <Stack direction="row" spacing={2} alignItems="center" justifyContent="space-between" sx={{ mb: 2 }}>
              <Typography variant="h6" gutterBottom sx={{ mb: 0 }}>
                AI-Generated Clinical Summary
              </Typography>
              <Button
                variant="outlined"
                size="small"
                startIcon={aiLoading ? <CircularProgress size={16} /> : <AutoAwesome />}
                onClick={handleGenerateAISummary}
                disabled={aiLoading || !results}
              >
                {aiLoading ? 'Generating...' : aiSummary ? 'Regenerate' : 'Generate AI Summary'}
              </Button>
            </Stack>
            {aiError && (
              <Alert severity="error" sx={{ mb: 2 }}>
                {aiError}
              </Alert>
            )}
            {aiSummary && (
              <Paper variant="outlined" sx={{ p: 2, backgroundColor: 'white', borderRadius: 1 }}>
                <Typography variant="body2" sx={{ whiteSpace: 'pre-wrap', lineHeight: 1.7 }}>
                  {aiSummary}
                </Typography>
              </Paper>
            )}
            {!aiSummary && !aiLoading && (
              <Typography variant="body2" color="text.secondary" sx={{ fontStyle: 'italic' }}>
                Click "Generate AI Summary" to add an AI-powered clinical interpretation to the dossier.
              </Typography>
            )}
          </Box>

          <Divider sx={{ my: 2 }} />

          {/* Patient Context */}
          <Typography variant="h6" gutterBottom>Patient Context</Typography>
          <Stack direction="row" spacing={1} sx={{ mb: 2 }}>
            <Chip label={formatDisease(diseaseContext.disease)} color="primary" />
            {diseaseContext.subtype && <Chip label={formatSubtype(diseaseContext.subtype)} variant="outlined" />}
            {diseaseContext.stage && <Chip label={`Stage ${diseaseContext.stage}`} variant="outlined" />}
          </Stack>

          {/* Mutations */}
          <Typography variant="h6" gutterBottom>Genetic Mutations</Typography>
          <TableContainer component={Paper} variant="outlined" sx={{ mb: 2 }}>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell><strong>Gene</strong></TableCell>
                  <TableCell><strong>Variant</strong></TableCell>
                  <TableCell><strong>Type</strong></TableCell>
                  <TableCell><strong>Origin</strong></TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {mutations.map((m, i) => (
                  <TableRow key={i}>
                    <TableCell><strong>{m.gene}</strong></TableCell>
                    <TableCell>{m.hgvs_p || '-'}</TableCell>
                    <TableCell>{formatConsequence(m.consequence)}</TableCell>
                    <TableCell>
                      <Chip
                        label={m.germline_status || 'Unknown'}
                        size="small"
                        color={m.germline_status === 'germline' ? 'secondary' : 'default'}
                      />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>

          {/* Essentiality Summary */}
          <Typography variant="h6" gutterBottom>Essentiality Scores</Typography>
          <Stack direction="row" spacing={2} sx={{ mb: 2 }}>
            {essentiality.map((e, i) => (
              <Paper key={i} variant="outlined" sx={{ p: 2, minWidth: 150 }}>
                <Typography variant="subtitle1" fontWeight="bold">{e.gene}</Typography>
                <Typography
                  variant="h4"
                  color={e.score >= 0.7 ? 'error.main' : e.score >= 0.5 ? 'warning.main' : 'success.main'}
                >
                  {(e.score * 100).toFixed(0)}%
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  {e.pathwayImpact}
                </Typography>
              </Paper>
            ))}
          </Stack>

          {/* Double-Hit Alert */}
          {pathways.double_hit_detected && (
            <Paper sx={{ p: 2, mb: 2, backgroundColor: 'error.lighter', border: '1px solid', borderColor: 'error.main' }}>
              <Typography variant="body1" fontWeight="bold" color="error.dark">
                🎯 Double-Hit Effect Detected
              </Typography>
              <Typography variant="body2" color="error.dark">
                Multiple pathway deficiencies create amplified synthetic lethality opportunity
              </Typography>
            </Paper>
          )}

          {/* Top Recommendation */}
          {therapies.length > 0 && (
            <>
              <Typography variant="h6" gutterBottom>Top Recommendation</Typography>
              <Paper sx={{ p: 2, backgroundColor: 'success.lighter', border: '2px solid', borderColor: 'success.main' }}>
                <Typography variant="h5" color="success.dark" fontWeight="bold">
                  {therapies[0].drug}
                </Typography>
                <Typography variant="body2" color="success.dark">
                  Target: {therapies[0].target} | Confidence: {(therapies[0].confidence * 100).toFixed(0)}% | 
                  {therapies[0].fda_approved ? ' FDA Approved ✓' : ' Clinical Trials'}
                </Typography>
                <Typography variant="body2" sx={{ mt: 1 }}>
                  {therapies[0].mechanism}
                </Typography>
              </Paper>
            </>
          )}
        </Paper>
      </DialogContent>

      <DialogActions sx={{ p: 2 }}>
        <Button startIcon={<ContentCopy />} onClick={handleCopy}>
          Copy
        </Button>
        <Button startIcon={<Download />} onClick={handleDownload}>
          Download
        </Button>
        <Button startIcon={<Print />} onClick={handlePrint}>
          Print
        </Button>
        <Button variant="contained" onClick={onClose}>
          Close
        </Button>
      </DialogActions>
    </Dialog>
  );
};

// Helper functions
function formatDisease(disease) {
  if (!disease) return 'Not specified';
  return disease.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

function formatSubtype(subtype) {
  if (!subtype) return '';
  return subtype.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

function formatConsequence(consequence) {
  if (!consequence) return 'Unknown';
  return consequence.replace('_variant', '').replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

function generateInterpretation(results, mutations) {
  const pathways = results.pathway_analysis || {};
  const therapies = results.recommended_therapies || [];
  const essentiality = results.essentiality || [];

  const parts = [];

  // Essentiality interpretation
  const highEss = essentiality.filter(e => e.score >= 0.7);
  if (highEss.length > 0) {
    parts.push(`**High Essentiality Detected:** ${highEss.map(e => e.gene).join(', ')} show high essentiality scores (≥70%), indicating complete or near-complete loss of function.`);
  }

  // Pathway interpretation
  if (pathways.broken_pathways?.length > 0) {
    parts.push(`**Pathway Deficiencies:** ${pathways.broken_pathways.join(', ')} pathway(s) are non-functional, creating cellular dependency on backup mechanisms.`);
  }

  // Double-hit interpretation
  if (pathways.double_hit_detected) {
    parts.push(`**Double-Hit Effect:** The combination of multiple pathway deficiencies creates amplified vulnerability to targeted therapy, supporting strong biological rationale for the recommended drugs.`);
  }

  // Therapy interpretation
  if (therapies.length > 0) {
    const topTherapy = therapies[0];
    parts.push(`**Therapeutic Opportunity:** ${topTherapy.drug} targeting ${topTherapy.target} is recommended with ${(topTherapy.confidence * 100).toFixed(0)}% confidence based on synthetic lethality with the identified pathway deficiencies.`);
  }

  return parts.join('\n\n');
}

export default ClinicalDossierModal;

