#!/usr/bin/env python3
"""
AUDIT SCRIPT: GSE165897 REPRODUCIBILITY CHECK
Requested by: Manager
Date: 2026-01-29

Objective: 
1. Load pathway_kinetics.csv (Exact values generated by pipeline)
2. Load PFI_DATA (Hardcoded ground truth outcome)
3. Merge and Compute Spearman Rho for DDR_Post vs PFI
4. Output EXACT CSV for audit
"""

import pandas as pd
import numpy as np
from scipy import stats
from pathlib import Path
import sys

# 1. HARDCODED PFI DATA (Ground Truth)
# Source: Zhang et al., 2022 / User Input
PFI_DATA = {
    'patient_id': ['EOC1005', 'EOC87', 'EOC136', 'EOC423', 'EOC568', 
                   'EOC648', 'EOC891', 'EOC991', 'EOC933', 'EOC1129', 'EOC1153'],
    'pfi_months': [4.2, 9.1, 7.0, 24.0, 7.0, 50.5, 6.1, 4.2, None, None, None],
    'resistant_label': ['Resistant', 'Sensitive', 'Sensitive', 'Sensitive', 'Sensitive',
                        'Sensitive', 'Sensitive', 'Resistant', 'Unknown', 'Unknown', 'Unknown']
}

def main():
    print("="*80)
    print("AUDIT: GSE165897 EXACT VALUES & CORRELATION")
    print("="*80)

    # 2. LOAD KINETICS DATA
    kinetics_path = Path("data/serial_sae/gse165897/results/pathway_kinetics.csv")
    if not kinetics_path.exists():
        print(f"❌ CRITICAL ERROR: {kinetics_path} does not exist.")
        return

    df_kinetics = pd.read_csv(kinetics_path)
    print(f"Loaded Kinetics Data: {len(df_kinetics)} patients found in CSV.")
    
    # 3. MERGE
    df_pfi = pd.DataFrame(PFI_DATA)
    merged = pd.merge(df_pfi, df_kinetics, on='patient_id', how='left')
    
    # 4. FILTER EVALUABLE (Has PFI and Has DDR_Post)
    evaluable = merged.dropna(subset=['pfi_months', 'ddr_post']).copy()
    
    print(f"Evaluable Intersection: {len(evaluable)} patients (Post-Treatment + Outcome)")
    print("-" * 80)
    
    # 5. DUMP TABLE
    audit_table = evaluable[['patient_id', 'pfi_months', 'resistant_label', 'ddr_pre', 'ddr_post', 'ddr_delta']].sort_values('pfi_months')
    print(audit_table.to_string(index=False))
    print("-" * 80)
    
    # 6. COMPUTE STATISTICS
    if len(audit_table) > 1:
        # Spearman Rho
        rho, p = stats.spearmanr(audit_table['pfi_months'], audit_table['ddr_post'])
        print(f"\nAUDIT RESULT: DDR_Post vs PFI")
        print(f"Spearman Rho = {rho:.4f}")
        print(f"P-value      = {p:.4f}")
        
        # Check Delta
        rho_d, p_d = stats.spearmanr(audit_table['pfi_months'], audit_table['ddr_delta'])
        print(f"\nAUDIT RESULT: DDR_Delta vs PFI")
        print(f"Spearman Rho = {rho_d:.4f}")
        print(f"P-value      = {p_d:.4f}")
        
    else:
        print("❌ Not enough data points for correlation.")

    # 7. GENERATE CSV ARTIFACT
    output_path = Path("data/serial_sae/gse165897/results/audit_gse165897_table.csv")
    audit_table['ddr_metric_type'] = "Activity (Expression Mean)"
    audit_table.to_csv(output_path, index=False)
    print(f"\n✅ Audit Table saved to: {output_path}")

if __name__ == "__main__":
    main()
