import os
import textwrap
import json

def main():
    """
    Generates the CORRECTED cURL command for the Boltz V2 Manual Validation Protocol.

    This script serves as the executable test case for validating the boltz-service,
    aligning with its true purpose as a BINDING AFFINITY PREDICTOR, not just
    a structural integrity checker.
    """
    
    # --- Test Case: BRAF Fragment vs. a slightly modified candidate ---
    target_protein_sequence = "MAALSGGGGGAEPGWVCLHGTLLPEPGGASKICGSGSFPHGLLVFWKVKGLLKMLADRVENTFPIPRVIRKQLHVQMLQYLEKHKIQSWIHVWMRDYHPFDRDQDHYAKGFVRYSVKNT"
    # For this test, our "candidate" is just a slightly shortened version of the target.
    # In a real run, this would be the protein generated by our Forge.
    candidate_protein_sequence = "MKTAVIKCVHWSASGALEGTRLTRVAYKAFRAARLYREMASPVENKFIQKHGEATEEKLKKSKALQQK"
    
    boltz_service_url = "https://crispro--boltz-service-fastapi-app.modal.run/v1/predict"

    # --- Construct the Correct JSON Payload ---
    # The service expects a list of 'entities'.
    # Entity 0 is the target, Entity 1 is the candidate.
    payload = {
        "entities": [
            {
                "name": "BRAF_target_fragment",
                "type": "protein",
                "sequence": target_protein_sequence
            },
            {
                "name": "candidate_inhibitor_test_v1",
                "type": "protein",
                "sequence": candidate_protein_sequence
            }
        ]
    }
    
    # Convert payload to a compact JSON string for the -d argument
    json_payload_str = json.dumps(payload)

    # Construct the cURL command
    curl_command = f"""
curl -X POST "{boltz_service_url}" \\
-H "Content-Type: application/json" \\
-d '{json_payload_str}'
"""

    # --- Print the Instructions ---
    print("--- ⚔️  BOLTZ V2: BINDING AFFINITY VALIDATION ⚔️  ---")
    print("\\nThis script provides the CORRECTED command to manually test our 'boltz-service'.")
    print("It validates its ability to predict binding affinity between a target and a candidate.")
    print("\\n------------------------------------------------------------------")
    print("  ✅ 1. TEST CASE DATA")
    print("------------------------------------------------------------------")
    print(f"  - Target Protein (BRAF Fragment):\\n    {textwrap.fill(target_protein_sequence, 60, initial_indent='    ', subsequent_indent='    ')}")
    print(f"  - Candidate Protein (Test):\\n    {textwrap.fill(candidate_protein_sequence, 60, initial_indent='    ', subsequent_indent='    ')}")
    print(f"  - Service Endpoint:\\n    {boltz_service_url}")
    print("\\n------------------------------------------------------------------")
    print("  ✅ 2. EXECUTE THIS COMMAND IN YOUR TERMINAL")
    print("------------------------------------------------------------------")
    print(curl_command.strip())
    print("\\n------------------------------------------------------------------")
    print("  ✅ 3. VERIFY THE RESULTS")
    print("------------------------------------------------------------------")
    print("  - The command should return a JSON object.")
    print("  - Look for the 'affinity_score' key.")
    print("  - A numeric score indicates a SUCCESSFUL run.")
    print("------------------------------------------------------------------\\n")

if __name__ == "__main__":
    main() 
import textwrap
import json

def main():
    """
    Generates the CORRECTED cURL command for the Boltz V2 Manual Validation Protocol.

    This script serves as the executable test case for validating the boltz-service,
    aligning with its true purpose as a BINDING AFFINITY PREDICTOR, not just
    a structural integrity checker.
    """
    
    # --- Test Case: BRAF Fragment vs. a slightly modified candidate ---
    target_protein_sequence = "MAALSGGGGGAEPGWVCLHGTLLPEPGGASKICGSGSFPHGLLVFWKVKGLLKMLADRVENTFPIPRVIRKQLHVQMLQYLEKHKIQSWIHVWMRDYHPFDRDQDHYAKGFVRYSVKNT"
    # For this test, our "candidate" is just a slightly shortened version of the target.
    # In a real run, this would be the protein generated by our Forge.
    candidate_protein_sequence = "MKTAVIKCVHWSASGALEGTRLTRVAYKAFRAARLYREMASPVENKFIQKHGEATEEKLKKSKALQQK"
    
    boltz_service_url = "https://crispro--boltz-service-fastapi-app.modal.run/v1/predict"

    # --- Construct the Correct JSON Payload ---
    # The service expects a list of 'entities'.
    # Entity 0 is the target, Entity 1 is the candidate.
    payload = {
        "entities": [
            {
                "name": "BRAF_target_fragment",
                "type": "protein",
                "sequence": target_protein_sequence
            },
            {
                "name": "candidate_inhibitor_test_v1",
                "type": "protein",
                "sequence": candidate_protein_sequence
            }
        ]
    }
    
    # Convert payload to a compact JSON string for the -d argument
    json_payload_str = json.dumps(payload)

    # Construct the cURL command
    curl_command = f"""
curl -X POST "{boltz_service_url}" \\
-H "Content-Type: application/json" \\
-d '{json_payload_str}'
"""

    # --- Print the Instructions ---
    print("--- ⚔️  BOLTZ V2: BINDING AFFINITY VALIDATION ⚔️  ---")
    print("\\nThis script provides the CORRECTED command to manually test our 'boltz-service'.")
    print("It validates its ability to predict binding affinity between a target and a candidate.")
    print("\\n------------------------------------------------------------------")
    print("  ✅ 1. TEST CASE DATA")
    print("------------------------------------------------------------------")
    print(f"  - Target Protein (BRAF Fragment):\\n    {textwrap.fill(target_protein_sequence, 60, initial_indent='    ', subsequent_indent='    ')}")
    print(f"  - Candidate Protein (Test):\\n    {textwrap.fill(candidate_protein_sequence, 60, initial_indent='    ', subsequent_indent='    ')}")
    print(f"  - Service Endpoint:\\n    {boltz_service_url}")
    print("\\n------------------------------------------------------------------")
    print("  ✅ 2. EXECUTE THIS COMMAND IN YOUR TERMINAL")
    print("------------------------------------------------------------------")
    print(curl_command.strip())
    print("\\n------------------------------------------------------------------")
    print("  ✅ 3. VERIFY THE RESULTS")
    print("------------------------------------------------------------------")
    print("  - The command should return a JSON object.")
    print("  - Look for the 'affinity_score' key.")
    print("  - A numeric score indicates a SUCCESSFUL run.")
    print("------------------------------------------------------------------\\n")

if __name__ == "__main__":
    main() 
 
 
 
 
 