import requests
import json
import sys
import os
from loguru import logger

# Add the project root to the Python path to allow importing from 'src'
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.tools.llm_api import query_llm # Import the LLM query function

# This assumes the command_center service is running locally via `modal serve`
# The local server URL is typically http://127.0.0.1:8000
COMMAND_CENTER_URL = "http://127.0.0.1:8000"
SYNTHESIZE_ENDPOINT = f"{COMMAND_CENTER_URL}/api/intelligence/synthesize"

def run_synthesis_test(target_domain: str, gene_context: str):
    """
    Calls the local command_center synthesis endpoint to test intelligence generation.
    """
    logger.info(f"--- 🔬 ZT-INTEL SYNTHESIS ENGINE LOCAL TEST 🔬 ---")
    logger.info(f"Querying for target domain: {target_domain}")

    payload = {
        "query": f"Provide a detailed analysis of the biological function and role in cancer of the protein domain: {target_domain}.",
        "content": f"Focus on its mechanism, involvement in signaling pathways, and its validity as a therapeutic target, particularly in the context of {gene_context}.",
        "user_id": "COMMANDER_ALPHA_TEST"
    }

    try:
        response = requests.post(SYNTHESIZE_ENDPOINT, json=payload, timeout=300) # 5 minute timeout for complex synthesis
        response.raise_for_status()  # Raise an exception for bad status codes
        
        data = response.json()

        logger.success("✅ Intelligence Synthesis Successful!")
        logger.info("--- 📄 RECEIVED DOSSIER 📄 ---")
        
        print("\n" + "="*50)
        print("TARGET DOSSIER FOR:", target_domain)
        print("="*50 + "\n")

        logger.info("📝 Summary:")
        print(data.get("summary", "No summary provided."))

        logger.info("\n🔑 Key Entities:")
        if data.get("entities"):
            for entity in data["entities"]:
                relevance_score = entity.get('relevance')
                relevance_str = f"{relevance_score:.2f}" if isinstance(relevance_score, (int, float)) else "N/A"
                print(f"  - {entity.get('name', 'Unknown Entity')} ({entity.get('type', 'Unknown Type')}) - Relevance: {relevance_str}")
        else:
            print("  - No entities identified.")

        logger.info("\n⚙️ Key Mechanisms:")
        if data.get("mechanisms"):
            for mechanism in data["mechanisms"]:
                print(f"  - {mechanism}")
        else:
            print("  - No mechanisms identified.")
        
        logger.info("\n💡 Key Conclusions:")
        if data.get("conclusions"):
            for conclusion in data["conclusions"]:
                print(f"  - {conclusion}")
        else:
            print("  - No conclusions drawn.")

        print("\n" + "="*50)


    except requests.exceptions.RequestException as e:
        logger.error(f"❌ Test Failed: Could not connect to the synthesis engine.")
        logger.error(f"  Error: {e}")
        logger.error(f"  Is the CommandCenter service running locally? Try: `modal serve services/command_center/main.py`")
    except json.JSONDecodeError:
        logger.error("❌ Test Failed: Failed to decode JSON response from the server.")
        print("Raw Response:", response.text)

    # --- Phase 2: AI Analyst Validation ---
    if 'data' in locals() and data:
        logger.info("--- 🧠 Engaging Secondary AI Analyst for Validation 🧠 ---")
        
        # Forge the prompt for the analyst
        analyst_prompt = f"""
        **Commander's Strategic Briefing Request**

        **Role:** You are a Senior Strategic Analyst with deep expertise in oncology, molecular biology, and therapeutic development.
        
        **Task:** Review the following intelligence dossier generated by a primary AI system. Synthesize all data points, cross-reference the findings for coherence, and produce a final strategic briefing for the Commander. Your briefing must be concise, actionable, and include a confidence assessment.

        **Input Intelligence Dossier for "{target_domain}" (in context of {gene_context}):**
        
        *   **Summary:** {data.get("summary", "N/A")}
        *   **Key Entities:** {json.dumps(data.get("entities", []), indent=2)}
        *   **Identified Mechanisms:** {'; '.join(data.get("mechanisms", ["N/A"]))}
        *   **Primary Conclusions:** {'; '.join(data.get("conclusions", ["N/A"]))}

        **Required Output Format (Strict):**

        1.  **Strategic Synthesis:** A single paragraph that integrates the key findings. What is the overarching story here?
        2.  **Target Value Assessment:** A clear "Go / No-Go" recommendation. Is this a strategically valuable target? Justify your answer in 1-2 sentences.
        3.  **Confidence Level:** High / Medium / Low.
        4.  **Justification:** Briefly explain your confidence level.
        """
        
        try:
            # Call the LLM with the forged prompt
            strategic_briefing = query_llm(analyst_prompt, provider="gemini")
            
            logger.success("✅ AI Analyst review complete.")
            print("\n" + "#"*60)
            print("## COMMANDER'S STRATEGIC BRIEFING ##")
            print("#"*60 + "\n")
            print(strategic_briefing)
            print("\n" + "#"*60)

        except Exception as e:
            logger.error(f"❌ AI Analyst Validation Failed.")
            logger.error(f"  Error during LLM call: {e}")


if __name__ == "__main__":
    target = "Peptidase M10"
    context = "MMP9"
    run_synthesis_test(target, context) 